apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30088 # Optional: Specify a custom NodePort, otherwise Kubernetes will assign one
  type: NodePort

